#!/bin/bash
# Cups backend to run Abaqus solver
# This file should be mode 500 so it runs as root
# Carl Osterwisch, September 2012
#
# Part of "Abacups" - See also:
# /usr/share/cups/mime/abaqus.types Mime type definition for abaqus-inp file
# /usr/share/cups/model/abaqus.ppd  Printer definition
# /usr/lib/cups/backend/abaqus      Cups backend to run Abaqus solver

# Output "device discovery" information on stdout:
if [ "$#" = "0" ]
then # device-class scheme "Unknown" "device-info" "device-id"
    echo 'direct abaqus: "abaqus" "Abaqus solver queue" "MFG:Abacups;MDL:Abaqus solver;CMD:none;"'
    exit 0
fi

# CUPS filter/backend arguments:
# $1 The job ID
# $2 The user printing the job
# $3 The job name/title
# $4 The number of copies
# $5 The options that were provided when the job was submitted
# $6 The file to print (blank for stdin)

# Parse options
for o in $5
do
    if [[ $o =~ abaqus=(.*) ]]
    then
        ABAQUSVER=${BASH_REMATCH[1]}
    fi
done
ABAQUS=/opt/abaqus/Commands/${ABAQUSVER-abaqus} # default

test -x $ABAQUS || { echo ERROR:\"$ABAQUS\" not executable>&2; exit 1; }

# Set INPUTFILE to where the input comes from:
test -n "$6" && INPUTFILE="$6" || INPUTFILE="-"

# This backend expects you to "print" the full path to an input file
read fullpath < "$INPUTFILE"
DIRNAME=$(dirname "$fullpath")
COMFILE=$(basename "$fullpath")

case $COMFILE in
    (*.com|*.COM) # Abaqus command file

        # How to terminate a running job? This doesn't seem to work.
        # trap 'kill $(jobs -p)' SIGTERM
        trap '$ABAQUS terminate job=${COMFILE%.com}' SIGTERM

	# Run as user $2
        su -l $2 -c "
            cd $DIRNAME
            $ABAQUS python \"$COMFILE\" |
            tee \"${COMFILE%.com}.log\" |
            gawk '{ print \"INFO:\"\$0 }'" >&2 # Report info to CUPS
        echo PAGE: 1 1 >&2
        ;;
    (*)
        echo ERROR:Unsupported filetype \"$COMFILE\">&2
        exit 1
        ;;
esac
