#!/bin/bash
# Cups filter to reformat text files as Abaqus-inp files by removing
# extra spaces added in Windows printer driver.
# Carl Osterwisch, September 2012
#
# Part of "Abacups" - See also:
# /usr/share/cups/mime/abaqus.convs Define filters to convert into abaqus-inp
# /usr/share/cups/mime/abaqus.types Mime type definition for abaqus-inp file
# /usr/share/cups/model/abaqus.ppd  Printer definition
# /usr/lib/cups/backend/abaqus      Cups backend to run Abaqus solver
# /usr/lib/cups/filter/texttoinp    Cups filter to reformat text into abaqus-inp

test -n "$6" && exec <"$6" # Redirect if filename was specified

/bin/sed -r '
s/^\s+//
s/\s+$//
/^$/d'
